### ISSUE TITLE
Overflow in computation with large integers

### ISSUE THREAD

**Issue by oscarbenjamin** [Mathics3/mathics-core#103]
This example is from the mathematica docs:
https://reference.wolfram.com/language/tutorial/DiophantineReduce.html

This calculation produces a large integer and then numerical evaluation overflows somehow:
```python
In[1]:= poly = x^100000 + 1234 x^77777 - 2121 x^12345 + 7890 x^999 - x^11
Out[1]:= -x ^ 11 + 7890 x ^ 999 - 2121 x ^ 12345 + 1234 x ^ 77777 + x ^ 100000

In[2]:= freeterm = poly /. x -> 1234567;
Out[2]:= None

In[3]:= N[freeterm]
General::ovfl: Overflow occurred in computation.
```
Also displaying `freeterm` is very slow.

By contrast with SymPy (not sure if SymPy is actually involved here):
```python
In [1]: poly = x**100000 + 1234* x**77777 - 2121* x**12345 + 7890* x**999 - x**11

In [2]: freeterm = poly.subs(x, 1234567)

In [3]: N(freeterm)
Out[3]: 2.92690499812734e+609151
```

**Comment by rocky** [comment]
If you set `$TraceEvaluation = True` you will the steps that Mathics is taking and get some sense of why it is slow. 

The variable "poly" is stored symbolically as a Mathics Expression, but freeterm isn't - all of those calculations in large precision are being done which is why freeterm is slow.  Of course change the `=` (Set) to `:=` (SetDelayed) but when you go to evaluate all of this with `N`, all of the expansion is done inside Mathics using calls I think to sympy.

**Comment by mmatera** [comment]
Actually, the evaluation is "fast":
![imagen](https://user-images.githubusercontent.com/2862288/148833194-583f51cc-2ebe-4015-a073-e3fd02d64db5.png)

what is very slow in Mathics  is to show the 609152 digits of the number.  WMA does it pretty fast, while the experiment in Sympy converts it to a floating point number. 

In Mathics, this last conversion produces the overflow, because the number is too large to be converted to a MachineReal number. I think this part is easy to fix (later I will send a PR to fix this).

**Comment by rocky** [comment]
See also https://github.com/Mathics3/mathics-core/discussions/111#discussioncomment-1960660
