### ISSUE TITLE
First with empty list crashes mathics

### ISSUE THREAD

**Issue by oscarbenjamin** [Mathics3/mathics-core#104]
Demo:
```
In[4]:= First[{}]
Traceback (most recent call last):
...
  File "/home/oscar/current/sympy/mathics-core/mathics/builtin/list/eol.py", line 434, in apply
    return expr.leaves[0]
IndexError: tuple index out of range
```
I guess there should be a handler for the case where the list is empty.

**Comment by rocky** [comment]
Seems pretty simple to address. I don't have Mathematica so I don't know what the behavior is though. 

Are you up for making a fix to the code?

**Comment by oscarbenjamin** [comment]
I don't have a proper dev setup for mathics. It's not immediately clear how to get it set up right now with everything split into components i.e. which versions of the different bits should I install while testing a change to mathics-core?

I should be clear that I am a SymPy maintainer and I have been experimenting with mathics because I wanted to learn more about Mathematica myself. I've been thinking about pattern matching and wanted to understand more about how it works in Mathematica (which I also don't have).

**Comment by rocky** [comment]
> I don't have a proper dev setup for mathics. It's not immediately clear how to get it set up right now with everything split into components i.e. which versions of the different bits should I install while testing a change to mathics-core?

For what you are doing the minimum is mathics-core, this repository. See https://mathics-development-guide.readthedocs.io/en/latest/installing/index.html

Installing it would be like many other python libraries 

```
python ./setup.py develop
``` 

or 

```
pip install -e .
```

> 
> I should be clear that I am a SymPy maintainer and I have been experimenting with mathics because I wanted to learn more about Mathematica myself. I've been thinking about pattern matching and wanted to understand more about how it works in Mathematica (which I also don't have).

Ok - fair enough. I should also be clear that as you have found it doesn't take long to find some bug in the code. It takes much longer to get it fixed and we don't have many people fixing. We have a lot of people in the reporting camp, so there is no shortage of work that needs to be done. 

As for Sympy integration of course, I'd like to see more and better use of that over time and have had some ideas.

**Comment by oscarbenjamin** [comment]
> As for Sympy integration of course, I'd like to see more and better use of that over time and have had some ideas.

Please involve me in any discussions along those lines.

**Comment by rocky** [comment]
> Please involve me in any discussions along those lines.

Before I got involved with this I toyed with the idea of taking Mathics and converting it to Sympy. See https://github.com/rocky/FoxySheep2    That line of approach might be okay for data-type conversions - convert data in Mathics form to Sympy/Python form and simple conversions.  Going further, a `Compile[]` mode might make use of something like this. 

Going further we could add `ToSympy[]` and `SympyForm` which are Sympy objects much like there is something for DateObject. Going further, when it makes sense that object could be saved in an Mathics Expression so that when further operations are done as in the case of `/.` / `.subs`  the evaluator can start with the Sympy representation instead of having to reinterpret the Mathics Expression.

This is all vapoware and much hand waving though. At some point I'll do some experiments and possibly devise a plan.

**Comment by mmatera** [comment]
```
Mathematica 12.2.0 Kernel for Linux x86 (64-bit)
Copyright 1988-2020 Wolfram Research, Inc.
Firs
In[1]:= First[{}]                                                               

First::nofirst: {} has zero length and no first element.

Out[1]= First[{}]
```
