### ISSUE TITLE
Expression evaluating to False

### ISSUE THREAD

**Issue by hrueter** [Mathics3/mathics-core#200]
### Observed behavior
```
In[1]:= g[2] == g[3]
Out[1]= False
```
### Expected behavior
```
In[1]:= g[2] == g[3]
Out[1]= g[2] == g[3]
```
### Background
In WL expression equations evaluating to `False` return the expression itself. Only the identity operator `===` should return `False` for expression equations. (For numerical evaluations also `==` can return `False`.)
### Setup
Linux Mint 20.3
Mathics 4.0.0 on CPython 3.8.10 (default, Nov 26 2021, 20:14:08)  using SymPy 1.8, mpmath 1.2.1, numpy 1.17.4
### Possible Fix
Fix `expr_equal` in https://github.com/Mathics3/mathics-core/blob/9eb8b1a47e69eea40c4ecf9532525649c0163e53/mathics/builtin/comparison.py#L110

returning `None` instead of `tst` fixes the behavior above.

**Comment by rocky** [comment]
Thanks for the thoughtful and detailed reports. We will look into it when we get a chance.

**Comment by rocky** [comment]
I took a quick look at this (when I should be doing other things), and although I see a simple fix here

```diff
diff --git a/mathics/builtin/comparison.py b/mathics/builtin/comparison.py
index b5b55b24..68bc8ded 100644
--- a/mathics/builtin/comparison.py
+++ b/mathics/builtin/comparison.py
@@ -184,7 +184,9 @@ class _EqualityOperator(_InequalityOperator):
         """
         if hasattr(lhs, "equal2"):
             result = lhs.equal2(rhs)
-            if result is not None:
+            if result is None:
+                return None
+            else:
                 return result
         elif lhs.sameQ(rhs):
             return True
```

This is incomplete since  it changes the behavor of `Pi == 3.14'` from `False` to the same expression. And what is needed here is to add an `equal2()` member function in the `_Constant_Common` class which understands comparison within precision. 

So now let me get back to the larger picture...

@hrueter If these issues are idle curiosity and noticed possibly because you are new to Mathics and just seeing what's there, let me say that there are probably a number of issues one can find like this and we have way more bug reporters than bug fixers.

Right now personally, I am interested and more focused on this long-standing problem that evaluation is way too slow and that's probably going to take a while to address. 

So if fixing this is something of interest to you, dig in. If the interest in this and the other issues is more than idle curiosity but is  blocker for something bigger, then stating this might change the bug-fixing priority.

We have

**Comment by hrueter** [comment]
It is indeed more than idle curiosity. I am working on numerical simulations of black holes and neutron stars. Some of our C code is automatically generated using Mathematica scripts. We wish to implement an option which allows to generate the C code also on systems that do not have Mathematica installed.

I found the reported issues, when I ran our code generation scripts with Mathics. Issues #200, #201 and #205
must be fixed, before we can adopt Mathics, since we cannot easily work around them.
Evaluation speed is not a top priority for us a the moment, since the time our code generation scripts need is still short compared to the overall runtime of our simulations.

**Comment by mmatera** [comment]
@hrueter, thanks for your detailed reports. Most of them seem more or less straightforward to fix, so I plan to do that during the following days.

**Comment by axkr** [comment]
> It is indeed more than idle curiosity. I am working on numerical simulations of black holes and neutron stars. Some of our C code is automatically generated using Mathematica scripts. We wish to implement an option which allows to generate the C code also on systems that do not have Mathematica installed.

you probably know the MathCompile project?
- https://github.com/njpipeorgan/MathCompile/wiki/Guide
