### ISSUE TITLE
Mathics crashes during Factor

### ISSUE THREAD

**Issue by hrueter** [Mathics3/mathics-core#231]
### Observed behavior
Mathics crashes from this input
```
In[1]:= a == d b + d c // Factor
```
### Expected behavior as in Mathematica
```
In[1]:= a == d b + d c // Factor
Out[1]= a == (b + c) d
```
### Setup
Linux Mint 20.3
Mathics 4.1.0.dev0 on CPython 3.8.10 (default, Nov 26 2021, 20:14:08)  using SymPy 1.8, mpmath 1.2.1, numpy 1.17.4

**Comment by TiagoCavalcante** [comment]
@hrueter by now you can use `a == (d b + d c // Factor)`. The precedence of the `//` or the `==` operator is wrong.

**Comment by TiagoCavalcante** [comment]
@rocky @mmatera this is very weird: we are doing this correctly, this is why it isn't working :-).

The precedence of `//` is 70 here and in WL, while the precedence of `==` is 290, now let's see a bit of [in]consistency:
```wl
Mathics:
In[1]:= FullForm[1 + b * 2]
Out[1]= Plus[1, Times[b, 2]]
In[2]:= Precedence[Plus]
Out[2]= 210.
In[3]:= Precedence[Times]
Out[3]= 400.
In[4]:= a == b // F
Out[4]= F[a == b]
In[5]:= Precedence[Equal]
Out[5]= 290.
In[6]:= Precedence[Postfix]
Out[6]= 70.

WL:
In[1]:= FullForm[1 + b * 2]
Out[1]= Plus[1, Times[b, 2]]
In[2]:= Precedence[Plus]
Out[2]= 210.
In[3]:= Precedence[Times]
Out[3]= 400.
In[4]:= a == b // F
Out[4]= a == F[b]
In[5]:= Precedence[Equal]
Out[5]= 290.
In[6]:= Precedence[Postfix]
Out[6]= 70.
```

Yep, the precedence is basically ignored in WL, but we don't do it. Now the bug is to assume that the Sympy expression can be written "as_numer_denom".
