### ISSUE TITLE
Problem with Collect[ , , ]

### ISSUE THREAD

**Issue by tmdbs** [Mathics3/mathics-core#285]
The Collect[ , , ]  command doesn't work well.

code:

Solve[Q[x,y]==1/6(x+y+1/x+1/y+y/x+x/y)(Q[x,y]-Q[x,0]-Q[0,y]+Q[0,0])+1/2(x+y)Q[0,0]+(1/3 x+1/6(y+1/x+y/x+1))(Q[x,0]-Q[0,0]) + (1/3 y+1/6(x+1/y+x/y+1))(Q[0,y]-Q[0,0]),Q[x,y]];
%[[1,1,2]]; 
Coefficient[%,Q[0,y]]//Factor//TeXForm
Collect[%%,Q[_,_],Factor]//TeXForm
(*I just solve an equation and first check the coefficient of Q[0,y], and then write it down*)

 and it gives:

-\frac{y \left(-1+x\right) \left(1+y\right)}{x+x^2+y-6 x y+x^2 y+y^2+x y^2}

\frac{Q\left[x,0\right] \left(-1-x-y\right) \left(-x-y+2 x y\right)}{x+x^2+y-6 x y+x^2 y+y^2+x y^2}

(*The coefficient of Q[0,y] exists, but Q[0,y] does not appear in the Collect[, ,] expression. Actually it doesn't work well for Collect[%%,Q[x,0],Factor] as well. gives some misterious results*)

## Your Environment
Mathics 4.0.0

**Comment by rocky** [comment]
I am sorry, but the expression of the problem is a bit too complex for me to want to even try to understand what's going on. I suspect that will be the case for others too. 

I lost you after the 4th `+` and in output after `\frac{y \left(`. 

I don't see that `TeXForm` formatting is adding anything here, unless there is a problem with TeX formatting. And if that's the case then that could probably be conveyed simpler and in a more isolated report. Rather it just makes things unnecessarily more complex. 

Some suggestions. Try to get this down to the simplest expression that has a problem. If you find the boundary of where the problem lies and changing anything succeeds, you might also be able to understand how to a workaround the problem. 

Using `TraceEvaluation[]`  you can see the steps going on in evaluation. But be warned if you write something complicated tracing its evaluation will be quite long and probably hard to understand. 

Finally, try writing this in pure SymPy. If there is a problem in SymPy's solution, Mathics will probably give the same result.

**Comment by Kalsofar** [comment]
Reduced test case:

```
Mathics 5.0.0.dev0
on CPython 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
using SymPy 1.10.1, mpmath 1.2.1, numpy 1.23.1

Copyright (C) 2011-2022 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by evaluating Quit[] or by pressing CONTROL-D.


In[1]:= Collect[ q[0, x] q[0, y] + 1, q[0, x] ]
Out[1]= 1 + q[0, y]
```

Expected output:
```
In[1]:= Collect[ q[0, x] q[0, y] + 1, q[0, x] ]
Out[1]= 1 + q[0, x] q[0, y]
```

Still investigating...

**Comment by rocky** [comment]
@Kalsofar the function `TraceEvaluation[]` may help in understanding the steps Mathics takes to get the result it gets.
