### ISSUE TITLE
Normal does not work

### ISSUE THREAD

**Issue by pietromenotti** [Mathics3/mathics-core#46]
Normal[Series[f[x],{x,0,1}]]

gives 

Normal[f[0] + f'[0] x + O[x] ^ 2]

instead of

f[0] + f'[0] x

**Comment by rocky** [comment]
It is not clear to me that this is incorrect, and it might be because underneath sympy is calculating this, and this is what sympy calculates.

If you are up to it, try rewriting this in sympy to see what it returns. In the future, we may add a debug option to trace sympy/mathmp/numpy calls and results to make this kind of thing more apparent. 

However _if_ this is what's going on, then to get this changed someone (perhaps even you) would have to go to the sympy folks to for clarification or bug fix if it is indeed a bug.

Lastly, let me clarify something about open-source projects in general versus say a product like Mathematica which is paid for. In this open source project no one is getting paid. You can sponsor some of the people sponsor the project, but unfortunately some people working on the project can't get paid there because of the country they live it. And right now the money that comes in from that is probably less than I make in 15 minutes of paid work. 

If your problem is sufficiently interesting, then someone may take interest and work on it. But chances are that's not going to happen. because there are so many _other_ problems with this code that those working on it might be more interested in fixing and may have a bigger impact. (If you think this is going to have a big impact, on the community, then say so.)

But the flip side of open-source projects is that everything is there for you to work on something that interests you and that you feel is wrong.
