### ISSUE TITLE
Old setup.py in new release (also scikit-image as optional requirement)

### ISSUE THREAD

**Issue by vicp74** [Mathics3/mathics-core#944]
## Description

The [tar.gz for release 6.0.4](https://github.com/Mathics3/mathics-core/releases/download/6.0.4/Mathics3-6.0.4.tar.gz) includes the old version of `setup.py`, as it was in 6.0.3.

## Additional context

I noticed this because `scikit-image` was added as a install requirement during release 6.0.3 at [line 44 of setup.py](https://github.com/Mathics3/mathics-core/blob/6.0.3/setup.py#L44). Then, for the next release it was silently dropped from [setup.py](https://github.com/Mathics3/mathics-core/blob/6.0.4/setup.py). Since I would like to keep `scikit-image` as optional (because it's heavy, I don't work with images, etc...) I would like to use this opportunity to ask what is the intended behaviour.

**Comment by rocky** [comment]
`setup.py` is correct, the SHA1 tag for it however was not correct.  The correct SHA1 is b0b7efe1 and the release tag has been corrected. 

The reason this is not optional was because tests were failing without this. Rather than go back and make it optional in say a 6.0.5, I think it better to wait for 7.0.0 go come out sometime in January when it will be optional again. Or use a in your distribution a modified 6.0.3 or 6.0.4.

**Comment by vicp74** [comment]
Understood. I'll keep packaging it for AUR as is, for the time being, since it'd be too much hassle to patch it if there're otherwise some test failing. I hope it becomes lighter again soon by making scikit-image optional as before then.

**Comment by rocky** [comment]
@vicp74 7.0.0 was released a while ago. Is this still a problem?

**Comment by vicp74** [comment]
@rocky this is not a problem anymore. I missed the fact that scikit-image is optional again, so I updated the AUR package accordingly. IMO this issue can be closed.

**Comment by rocky** [comment]
@vicp74  Thanks for maintaining and updating the AUR package.
